version: '3.8'
services:
  web:
    build:
      context: .
    restart: always
    container_name: indian-coffee
    ports:
      - "3000:3000"

# docker build -t NOM_IMAGE .
# docker run -p 3000:3000 NOM_IMAGE
# docker-compose up