export { default as Layout } from './Layout';
export { default as Footer } from './Footer';
export { default as Plat } from './Plat';
export { default as SousPlat } from './SousPlat';
export { default as HeroBanner } from './HeroBanner';
export { default as Navbar } from './Navbar';
export { default as Discover } from './Discover';
export { default as DescBanner } from './DescBanner';
export { default as DeliciousSection } from './DeliciousSection';
