import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { Plat, SousPlat } from '../../components';

const desserts = () => {
  return (
    <>
      <Head>
        <title>Plats | Indian Cofee Shop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <section className='w-full items-center justify-center text-white'>
        <Image
          src='/IndianCoffee_Logo.png'
          width={150}
          height={150}
          alt='logo'
        />

        <div className='pl-4 pr-4'>
          <h1 className='uppercase text-[#e8b755] text-2xl font-bold tracking-wider mb-2'>
            Desserts
          </h1>
          <Plat
            title='KESARI'
            details='GÂTEAU DE SEMOULE AUX NOIX DE CAJOU & RAISINS SECS'
            price='4.00€'
          />
          <Plat
            title='GULAB JAMOUNE'
            details="BOULETTE DE PÂTE D'AMANDE DANS UN SIROP DE CARDAMONE"
            price='4,50€'
          />
          <Plat
            title='KULFI'
            details="GLACE À L'INDIENNE À LA MANGUE OU À LA PISTACHE"
            price='4,50€'
          />
          <Plat
            title='PAYASAM'
            details='BILLES DE TAPIOCA, LAIT DE COCO & NOIX DE CAJOU'
            price='4,00€'
          />
          <Plat
            title='FALOODA'
            details='LAIT, SIROP DE ROSE, GRAINES DE BASILIC, MORCEAUX DE GÉLATINE, BOULE DE GLACE'
            price='6,00€'
          />
          <Plat title='TIRAMISU' details='' price='6,90€' />
          <Plat title='TARTE TATIN' details='' price='8,50€' />
          <Plat
            title='FONDANT AU CHOCOLAT'
            details='CŒUR COULANT DE CHOCOLAT, BEURRE, OEUF, FARINE, SUCRE'
            price='5,50€'
          />
          <Plat
            title='COCKTAIL DE FRUITS'
            details='SALADE DE FRUITS FRAIS AVEC DE LA GLACE À LA VANILLE'
            price='5,50€'
          />
          <div className='mb-2'>
            <Plat title='CRÊPES' details='' price='' />
            <SousPlat title='NATURE' details='' price='3,00€' />
            <SousPlat title='SUCRE' details='' price='3,50€' />
            <SousPlat title='NUTELLA' details='' price='4,50€' />
            <SousPlat title='NUTELLA BANANE' details='' price='5,00€' />
          </div>

          <Plat title='THE GOURMAND' details='' price='8,50€' />
          <Plat title='CAFE GOURMAND' details='' price='7,90€' />

          <div className='mb-2'>
            <Plat
              title='COUPE DE GLACE'
              details='BOULE DE GLACE AU CHOIX: VANILLE, CHOCOLAT, MANGUE, COCO, CAFÉ, PISTACHE OU FRAISE'
              price=''
            />
            <SousPlat title='1 BOULE' details='' price='3,00€' />
            <SousPlat title='2 BOULES' details='' price='5,00€' />
          </div>

          <Plat title='BANANA SPLIT' details='' price='7,90€' />
          <Plat title='CHOCOLAT LIEGOIS' details='' price='7,90€' />
          <Plat title='DAME BLANCHE' details='' price='7,90€' />
          <Plat title='MANGO COCO' details='' price='7,90€' />
          <Plat title='PISTACHIO' details='' price='7,90€' />
        </div>
      </section>
    </>
  );
};

export default desserts;
