import Head from 'next/head';
import Image from 'next/image';
import React from 'react';

const menus = () => {
  return (
    <>
      <Head>
        <title>Menus | Indian Cofee</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <section className='w-full items-center justify-center text-white'>
        <Image
          src='/IndianCoffee_Logo.png'
          width={150}
          height={150}
          alt='logo'
        />

        <div className='pl-4 pr-4'>
          <h1 className='uppercase text-[#e8b755] text-2xl font-bold tracking-wider mb-2'>
            Menus
          </h1>
          <h2 className='text-center uppercase first-letter:text-3xl font-semibold text-xl text-[#e8be55]'>
            Menu végétarien – 15,90€
          </h2>
          <h3 className='mt-4 text-center first-letter:capitalize font-semibold text-xl text-[#a27e21]'>
            Entrée au choix
          </h3>
          <h4 className='text-center uppercase first-letter:text-xl font-semibold text-sm text-white'>
            Badji aubergines ou pomme de terre ou oignons ou Samossas légumes
          </h4>
          <h3 className='mt-4 text-center first-letter:capitalize font-semibold text-xl text-[#a27e21]'>
            Plat au choix
          </h3>
          <h4 className='text-center uppercase font-semibold text-sm text-white'>
            <ul>
              <li className='first-letter:text-xl'>
                Thali ( riz avec 5 sauces)
              </li>
              <li className='first-letter:text-xl'>
                Dal ( lentilles) avec riz basmati
              </li>
              <li className='first-letter:text-xl'>
                Massala dosa ( crêpe salée avec pomme de terre)
              </li>
            </ul>
          </h4>
          <h3 className='mt-4 text-center first-letter:capitalize font-semibold text-xl text-[#a27e21]'>
            Dessert au choix
          </h3>
          <h4 className='text-center uppercase first-letter:text-xl font-semibold text-sm text-white'>
            Payasam ou kessari (gateau de semoule)
          </h4>

          <h2 className='mt-8 text-center uppercase first-letter:text-3xl font-semibold text-xl text-[#e8be55]'>
            Menu Indian Cofee - 15,90€
          </h2>
          <h3 className='mt-4 text-center first-letter:capitalize font-semibold text-xl text-[#a27e21]'>
            Entrée au choix
          </h3>
          <h4 className='text-center uppercase font-semibold text-sm text-white'>
            <ul>
              <li className='first-letter:text-xl'>Tandoori poulet</li>
              <li className='first-letter:text-xl'>Rolls viande</li>
              <li className='first-letter:text-xl'>Samossa viande</li>
              <li className='first-letter:text-xl'>
                Badji pomme de terre ou oignons
              </li>
            </ul>
          </h4>
          <h3 className='mt-4 text-center first-letter:capitalize font-semibold text-xl text-[#a27e21]'>
            Plat au choix
          </h3>
          <h4 className='text-center uppercase font-semibold text-sm text-white'>
            <ul>
              <li className='first-letter:text-xl'>
                Briyani poulet ou agneau ou légumes
              </li>
              <li className='first-letter:text-xl'>Curry au poulet avec riz</li>
            </ul>
          </h4>
          <h3 className='mt-4 text-center first-letter:capitalize font-semibold text-xl text-[#a27e21]'>
            Dessert au choix
          </h3>
          <h4 className='text-center uppercase font-semibold text-sm text-white'>
            <ul>
              <li className='first-letter:text-xl'>Gulab jamoune</li>
              <li className='first-letter:text-xl'>
                kesari (gateau de semoule)
              </li>
              <li className='first-letter:text-xl'>Payasam</li>
            </ul>
          </h4>

          <h2 className='mt-8 text-center uppercase first-letter:text-3xl font-semibold text-xl text-[#e8be55]'>
            Menu Enfant – 8,90€
          </h2>
          <h3 className='mt-4 text-center first-letter:capitalize font-semibold text-xl text-[#a27e21]'>
            Plat au choix
          </h3>
          <h4 className='text-center uppercase font-semibold text-sm text-white'>
            <ul>
              <li className='first-letter:text-xl'>
                Riz Blanc et sauce kourouma
              </li>
              <li className='first-letter:text-xl'>Nuggets et frites</li>
            </ul>
          </h4>
          <h3 className='mt-4 text-center first-letter:capitalize font-semibold text-xl text-[#a27e21]'>
            Dessert au choix
          </h3>
          <h4 className='text-center uppercase font-semibold text-sm text-white'>
            <ul>
              <li className='first-letter:text-xl'>Boule de Glace</li>
              <li className='first-letter:text-xl'>Compote de pomme</li>
            </ul>
          </h4>
          <h3 className='mt-4 text-center first-letter:capitalize font-semibold text-xl text-[#a27e21]'>
            Boisson au choix
          </h3>
          <h4 className='text-center uppercase font-semibold text-sm text-white'>
            <ul>
              <li className='first-letter:text-xl'>Multi fruits</li>
              <li className='first-letter:text-xl'>jus de Pomme</li>
            </ul>
          </h4>
        </div>
      </section>
    </>
  );
};

export default menus;
