import Head from 'next/head';
import Image from 'next/image';
import { Plat, SousPlat } from '../../components';

const plats = () => {
  return (
    <>
      <Head>
        <title>Plats | Indian Cofee Shop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <section className='w-full items-center justify-center text-white'>
        <Image
          src='/IndianCoffee_Logo.png'
          width={150}
          height={150}
          alt='logo'
        />
        <div className='pl-4 pr-4'>
          <h1 className='uppercase text-[#e8b755] text-2xl font-bold tracking-wider mb-2'>
            plats
          </h1>

          <div className='mb-2'>
            <Plat
              title='SAUCE VINDALOO'
              details="SAUCE COMPOSÉ D'ÉPICES, PIMENTÉE POUR LES AMATEURS DE SENSATIONS FORTES SERVIE SANS ACCOMPAGNEMENT"
              price=''
            />
            <SousPlat title='POULET' price='8,00€' details='' />
            <SousPlat title='AGNEAU' price='9,50€' details='' />
            <SousPlat title='CREVETTES' price='11,00€' details='' />
            <SousPlat title='GAMBAS' price='14,00€' details='' />
            <SousPlat title='SAUMON' price='12,00€' details='' />
          </div>

          <div className='mb-2'>
            <Plat
              title='SAUCE CURRY'
              details="SAUCE PARFUMÉE D'ÉPICES TRADITIONNELLES AU GOÛT ENVOUTANT D'INDE SERVIE SANS ACCOMPAGNEMENT"
              price=''
            />
            <SousPlat title='POULET' price='8,00€' details='' />
            <SousPlat title='AGNEAU' price='9,50€' details='' />
            <SousPlat title='CREVETTES' price='11,00€' details='' />
            <SousPlat title='GAMBAS' price='14,00€' details='' />
            <SousPlat title='SAUMON' price='12,00€' details='' />
          </div>

          <div className='mb-2'>
            <Plat
              title='SAUCE KOUROUMA'
              details="SAUCE COMPOSÉ D'ÉPICES DOUCES ET PARFUMÉ AU LAIT DE COCO SERVIE SANS ACCOMPAGNEMENT"
              price=''
            />
            <SousPlat title='POULET' price='8,00€' details='' />
            <SousPlat title='AGNEAU' price='9,50€' details='' />
            <SousPlat title='CREVETTES' price='11,00€' details='' />
            <SousPlat title='GAMBAS' price='14,00€' details='' />
          </div>

          <div className='mb-2'>
            <Plat
              title='TIKKA MASSALA'
              details="MÉLANGE D'ÉPICES INDIENNES, OIGNONS ET POIVRONS"
              price=''
            />
            <SousPlat title='POULET' price='12,50€' details='' />
            <SousPlat title='AGNEAU' price='15,00€' details='' />
            <SousPlat title='GAMBAS' price='18,00€' details='' />
            <SousPlat title='SAUMON' price='15,00€' details='' />
          </div>

          <div className='mb-2'>
            <Plat
              title='KOTTU'
              details='EMINCÉES DE BAROTTA AVEC OEUF OU VIANDE '
              price=''
            />
            <SousPlat title='AGNEAU' price='10,00€' details='' />
            <SousPlat title='BOEUFS' price='10,00€' details='' />
            <SousPlat title='OEUFS' price='8,00€' details='' />
          </div>

          <div className='mb-2'>
            <Plat
              title='BIRYANI'
              details="MÉLANGE DE RIZ SAFRANÉ, DE TOMATES, D'OIGNONS AUX GINGEMBRE ET ÉPICE INDIENNE"
              price=''
            />
            <SousPlat title='POULET' price='10,00€' details='' />
            <SousPlat title='AGNEAU' price='14,00€' details='' />
            <SousPlat title='CREVETTES' price='13,00€' details='' />
            <SousPlat title='GAMBAS' price='18,00€' details='' />
            <SousPlat title='LÉGUMES' price='9,00€' details='' />
          </div>
        </div>
      </section>
    </>
  );
};

export default plats;
