import Head from 'next/head';
import Image from 'next/image';
import { Plat, SousPlat } from '../../components';

const specialites = () => {
  return (
    <>
      <Head>
        <title>Plats | Indian Cofee Shop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <section className='w-full items-center justify-center text-white'>
        <Image
          src='/IndianCoffee_Logo.png'
          width={150}
          height={150}
          alt='logo'
        />

        <div className='pl-4 pr-4'>
          <h1 className='uppercase text-[#e8b755] text-2xl font-bold tracking-wider mb-2'>
            spécialités
          </h1>

          <Plat
            title='BUTTER CHICKEN'
            details='POULET AU BEURRE ET RIZ BASMATI'
            price='13,50€'
          />
          <Plat
            title="CURRY D'AGNEAU AUX ÉPINARDS"
            details="CURRY D'AGNEAU ET RIZ BASMATI"
            price='15,50€'
          />
          <Plat
            title='FRIED RICE POULET'
            details='RIZ SAUTÉ AVEC POULET ET LÉGUMES'
            price='13,00€'
          />
          <Plat
            title='FRIED RICE ROYAL'
            details='POULET FRIT ET ÉPICÉ'
            price='9,00€'
          />
          <Plat
            title='CHILI CHICKEN'
            details='POULET FRIT ET ÉPICÉ, SAUCE CHILI'
            price='9,00€€'
          />
          <Plat
            title='BEEF DEVAL'
            details='BOEUF SAUTÉ AUX ÉPICES'
            price='16,00€'
          />
          <Plat
            title='DORADE ROYALE ENTIÈRE'
            details='POISSON MARINÉ AUX ÉPICES, GRILLÉ AU FOUR TANDOOR SERVI AVEC DU RIZ'
            price='19,90€'
          />
          <div className='mb-2'>
            <Plat title='GARNITURES ET ACCOMPAGNEMENTS' details='' price='' />
            <SousPlat title='NAAN AU FROMAGE' details='' price='4,00€' />
            <SousPlat title='NAAN NATURE' details='' price='2,50€' />
            <SousPlat title='NAAN À L’AIL' details='' price='3,00€' />
            <SousPlat title='KEEMA NAAN' details='' price='4,50€' />
            <SousPlat title='BAROTTHA' details='' price='2,00€' />
            <SousPlat title='CHAPATTY' details='' price='2,00€' />
            <SousPlat title='RIZ BASMATI NATURE' details='' price='2,50€' />
            <SousPlat title='RIZ SUPREME' details='' price='3,00€' />
            <SousPlat title='RIZ COCO' details='' price='3,00€' />
          </div>
        </div>
      </section>
    </>
  );
};

export default specialites;
