import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import { BsFacebook, BsInstagram, BsTelephone } from 'react-icons/bs';

export default function Home() {
  const [info, setInfo] = useState(3);

  const handleClick = (number: number) => {
    if (number === 1) setInfo(1);
    else if (number === 2) setInfo(2);
    else if (number === 3) setInfo(3);
  };
  return (
    <>
      <Head>
        <title>Accueil | Indian Cofee Shop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <section className='h-[100vh] w-full items-center justify-center bg-phonetel'>
        <Image
          src='/IndianCoffee_Logo.png'
          width={200}
          height={200}
          alt='logo'
          className='m-auto mb-8'
        />

        <h1 className='text-6xl text-white font-normal font-samarkan text-center'>
          Menu
        </h1>
        <div className='flex flex-col text-white bottom-0 absolute mb-4 left-0'>
          <p className='uppercase text-sm font-semibold mb-4 w-1/2 ml-4'>
            8 IMPASSE DE L'ORÉE DU BOIS 77176 SAVIGNY LE TEMPLE
          </p>
          <div className='flex flex-row ml-4 items-center'>
            <BsInstagram
              className='text-[#d5b130] text-5xl mr-4 cursor-pointer'
              onClick={() => handleClick(1)}
            />
            {info === 1 && (
              <Link href='https://www.instagram.com/indiancoffee77/'>
                <div className='mr-4 p-2 bg-[#333] rounded-xl'>
                  <p className='uppercase text-sm font-semibold'>
                    Notre Instagram
                  </p>
                  <p className='text-center text-sm'>indiancofee77</p>
                </div>
              </Link>
            )}
            <BsFacebook
              className='text-[#d5b130] text-5xl mr-4 cursor-pointer'
              onClick={() => handleClick(2)}
            />
            {info === 2 && (
              <Link href='https://www.facebook.com/profile.php?id=100083047666745'>
                <div className='mr-4 p-2 bg-[#333] rounded-xl'>
                  <p className='uppercase text-sm font-semibold'>
                    Notre Facebook
                  </p>
                  <p className='capitalize text-center text-sm'>Indian Cofee</p>
                </div>
              </Link>
            )}
            <BsTelephone
              className='text-[#d5b130] text-5xl mr-4 cursor-pointer'
              onClick={() => handleClick(3)}
            />
            {info === 3 && (
              <div className='mr-4 p-2 bg-[#333] rounded-xl'>
                <p className='uppercase text-sm font-semibold'>
                  Nous contacter
                </p>
                <p className='capitalize text-center text-sm'>
                  +33 (0)1 60 63 54 97
                </p>
              </div>
            )}
          </div>
        </div>
      </section>
    </>
  );
}
