import Head from 'next/head';
import Image from 'next/image';
import { BsFacebook, BsInstagram } from 'react-icons/bs';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Accueil | Indian Cofee Shop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <section className='h-[100vh] w-full items-center justify-center bg-phonetel'>
        <Image
          src='/IndianCoffee_Logo.png'
          width={200}
          height={200}
          alt='logo'
          className='m-auto mb-8'
        />
        <h1 className='text-6xl text-white font-normal font-samarkan text-center'>
          Menu
        </h1>

        <div className='flex flex-row ml-4 text-white bottom-0 absolute mb-4 left-0'>
          <BsFacebook className='text-[#d5b130] text-3xl mr-4' />
          <BsInstagram className='text-[#d5b130] text-3xl' />
        </div>
      </section>
    </div>
  );
}
